# Individual Assignment 2

In [8]:
import pandas as pd

# Read in the CSV file into the dataframe
train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")

# Print out only the first 10 lines
print(train.head(10))
print(test.head(10))

# Print the number of missing values
print(train.isna().sum())
print(test.isna().sum())

# Replace empty cells with null
train.fillna("null", inplace=True)
test.fillna("null", inplace=True)

# Get random sample of n length
train = train.sample(n = 4000, random_state=90713366)

   Index  Sentiment                                               Text
0      0          0  @switchfoot http://twitpic.com/2y1zl - Awww, t...
1      1          0  is upset that he can't update his Facebook by ...
2      2          0  @Kenichan I dived many times for the ball. Man...
3      3          0    my whole body feels itchy and like its on fire 
4      4          0  @nationwideclass no, it's not behaving at all....
5      5          0                      @Kwesidei not the whole crew 
6      6          0                                        Need a hug 
7      7          0  @LOLTrish hey  long time no see! Yes.. Rains a...
8      8          0               @Tatiana_K nope they didn't have it 
9      9          0                          @twittera que me muera ? 
   Index  Sentiment                                               Text
0      0          1  @stellargirl I loooooooovvvvvveee my Kindle2. ...
1      1          1  Reading my kindle2...  Love it... Lee childs i...
2     

# Text preprocessing

In [9]:
import re

# Create empty array for the first step
step_1_corpus = []

# Add to corpus array as lowercased
for sentence in train["Text"]:
    print(sentence)
    step_1_corpus.append(sentence.lower())

# Create empty array for the second step
step_2_corpus = []

# Remove the digits in the sentences 
for sentence in step_1_corpus:
    sentence = re.sub("[0-9]", "", sentence)
    step_2_corpus.append(sentence)

# Create empty array for the third step
step_3_corpus = []

# Fix contractions to be seperate words 
for sentence in step_2_corpus:
    sentence = re.sub(r"\'t", " not", sentence)
    sentence = re.sub(r"\'ve", " have", sentence)
    sentence = re.sub(r"\'s", " is", sentence)
    sentence = re.sub(r"\'re", " are", sentence)
    sentence = re.sub(r"can\'t", " can not", sentence)
    sentence = re.sub(r"\'ll", " will", sentence)
    sentence = re.sub(r"\'m", " am", sentence)
    sentence = re.sub(r"\'d", " would", sentence)
    sentence = re.sub(r"won\'t", " will not", sentence)

    step_3_corpus.append(sentence)


# Create empty array for the fourth step
step_4_corpus = []

for sentence in step_3_corpus:
    sentence = re.sub("[^a-z<> ]", "", sentence)
    step_4_corpus.append(sentence)

corpus = step_4_corpus

@Breezyroo nope i didnt get to see steph at all, closest i came was seeing her bus pull in.  didnt get to see her   but loved paul's chest
@bethchen1 Thanks for the #FF 
Today is just plain nasty out 
she did. her telepathy clairvoyant powers are stronger than mine. 
@kellidickinson deep deep down, not only am i not jealous, but you're gay 
2day started off soooo Bad!! 
@mimibadass oh god then that means im next. 
I'm sad that the Cav's lost... I really like Lebron 
Hit and run is no fun   My car got hit so badly it went 20 meters after the hit, and the stupid ##$@ other car simply ran away.
Add me i don't know how this works 
fighting with samsung D600. Losing 
is sadly awake 
Sims 3! Sims 3, Sims 3! Now off to work for a few hours 
@iamAnis i know aye...  damned not big countires like USA xDD
Ok ... Not feeling too good. Limbs weak.. Sore throat.... 
@jeflux totally.. i agree 
@KNichole25 i thought u were coming to see me 
Jumping on to say hello. Super busy.  if you've sent me an em

# Linguistic Feature Extraction

## Bag of words

In [10]:
import nltk
import numpy
from nltk.corpus import stopwords

#try:
#    _create_unverified_https_context = ssl._create_unverified_context
#except AttributeError:
#    pass
#else:
#    ssl._create_default_https_context = _create_unverified_https_context
#nltk.download()

# Set the stopwords to english stop words
stop_words = set(stopwords.words("english"))

# Create empty array
new_corpus = []

# Make the sentences that get appended to the new array without the stop words
for sentence in corpus:
    sentence = [w for w  in sentence.split() if not w in stopwords.words("english")]
    new_corpus.append(sentence)

corpus_stop = []

for words in new_corpus:
    sentence = " ".join(words)
    corpus_stop.append(sentence)
# Print new corpus with no stopwords
print(corpus_stop)

word2count = {}

for sentence in corpus_stop:
    # This tokenizes the sentences, which means it gets the words as the elements
    words = nltk.word_tokenize(sentence)

    # Loop through the words in the array and also adding them to dictionary to count how many times it appears
    for word in words:
        if word not in word2count.keys():
            word2count[word] = 1
        else:
            word2count[word] += 1

# Create list of unique words 
unique_words = list(word2count.keys())

# Create empty array of bag of words
bag_of_words = []

for sentence in corpus_stop:

    # Tokenizes each word in the sentence it is passed into
    words = nltk.word_tokenize(sentence)

    # This function creates an array with zeros with the length the size of the unique words array
    bag_vector = numpy.zeros(len(unique_words))

    for w in words:
        for i, word in enumerate(unique_words):
            if word == w:
                bag_vector[i] += 1

    # Finally appends words in the bag_vector into bag of words
    bag_of_words.append(bag_vector)
print(bag_of_words)

['breezyroo nope didnt get see steph closest came seeing bus pull didnt get see loved paul chest', 'bethchen thanks ff', 'today plain nasty', 'telepathy clairvoyant powers stronger mine', 'kellidickinson deep deep jealous gay', 'day started soooo bad', 'mimibadass oh god means im next', 'sad cav lost really like lebron', 'hit run fun car got hit badly went meters hit stupid car simply ran away', 'add know works', 'fighting samsung losing', 'sadly awake', 'sims sims sims work hours', 'iamanis know aye damned big countires like usa xdd', 'ok feeling good limbs weak sore throat', 'jeflux totally agree', 'knichole thought u coming see', 'jumping say hello super busy sent email dm behind respond soon good one', 'arms hurt today helping chop tree farm hate getting old', 'got clareashford black cloud following', 'miss miley cyrus always makes cry', 'havent seen savanah since wednesday', 'died lightningin sims', 'blogbabygabby loved pinky brain teenage mutant ninja turtles make cartoons like a

## TF * IDF

In [11]:
# import pandas

# # Empty set of words that won't have duplicates due to the nature of sets
# set_of_words = set()


# for doc in corpus_stop:
#     words = doc.split(" ")
#     set_of_words = set_of_words.union(set(words))

# list_of_words = list(set_of_words)

# number_of_documents = len(corpus_stop)
# number_of_set_of_words = len(set_of_words)

# df_tf = pd.DataFrame(numpy.zeros((number_of_documents, number_of_set_of_words)), columns=list_of_words)

# for i in range(number_of_documents):
#     words = corpus_stop[i].split(" ")
#     for w in words:
#         df_tf[w][i] = df_tf[w][i] + (1/len(words))

# idf = {}

# for w in set_of_words:
#     k = 0

#     for i in range(number_of_documents):
#         if w in corpus_stop[i].split():
#             k+=1
#     idf[w] = numpy.log10(number_of_documents/k)

# df_tf_idf = df_tf.copy()

# for w in list_of_words:
#     for i in range(number_of_documents):
#         df_tf_idf[w][i] = df_tf_idf[w][i] * idf[w]

# print(df_tf_idf)
from sklearn.feature_extraction.text import TfidfVectorizer

# The sklearn library has a built in function to get the TF * IDF values
tf_idf_model = TfidfVectorizer()

# Preform a fit transform to the corpus_stop array
tf_idf_vector = tf_idf_model.fit_transform(corpus_stop)

# Array-ify the vector
tf_idf_array = tf_idf_vector.toarray()

print(tf_idf_array)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


## Word2Vec

In [5]:
from gensim.models import Word2Vec

# Tokenized the words into a list so the words are the elements
tokenized_corpus = [nltk.word_tokenize(sentence) for sentence in corpus]

# The word2vec built-in function does what we need it to do so it is used
model = Word2Vec(sentences=tokenized_corpus, vector_size=100, window=5, min_count=1, workers=4)

print(model.wv.index_to_key)

['i', 'to', 'the', 'is', 'my', 'a', 'not', 'and', 'it', 'you', 'in', 'am', 'for', 'have', 'of', 'that', 'me', 'on', 'but', 'so', 'just', 'was', 'be', 'at', 'are', 'can', 'this', 'with', 'now', 'will', 'up', 'out', 'all', 'like', 'no', 'get', 'day', 'go', 'too', 'got', 'work', 'going', 'today', 'do', 'back', 'good', 'from', 'what', 'im', 'really', 'about', 'don', 'time', 'your', 'we', 'its', 'one', 'still', 'had', 'he', 'na', 'love', 'want', 'lol', 'they', 'wish', 'think', 'how', 'miss', 'know', 'home', 'need', 'u', 'sad', 'well', 'bad', 'see', 'as', 'why', 'there', 'been', 'oh', 'some', 'would', 'has', 'she', 'when', 'amp', 'her', 'much', 'an', 'new', 'sorry', 'twitter', 'if', 'last', 'feel', 'here', 'night', 'again', 'more', 'or', 'sleep', 'tomorrow', 'thanks', 'off', 'morning', 'gon', 'only', 'make', 'by', 'then', 'fun', 'haha', 'getting', 'didn', 'hate', 'right', 'tonight', 'them', 'sick', 'people', 'could', 'school', 'should', 'did', 'hope', 'very', 'yeah', 'come', 'never', 'though

# Sentiment Classification Model

In [ ]:
form 